version: "3.8"

services:
  meilisearch:
    image: getmeili/meilisearch:v1.5
    restart: always
    ports:
      - "7700:7700"
    environment:
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ENV: production
    volumes:
      - meili_data:/meili_data

volumes:
  meili_data:
