services:
  - type: web
    name: meilisearch
    env: docker
    plan: free
    dockerImage: getmeili/meilisearch:v1.5
    startCommand: ""
    autoDeploy: true
    envVars:
      - key: MEILI_MASTER_KEY
        value: supersecret123
      - key: MEILI_ENV
        value: production
